# Generated by Django 2.1.4 on 2019-07-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
