# Generated by Django 2.1.4 on 2019-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20190711_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='Antalldrer',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Antalleiere',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Antallseter',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Avgiftsklasse',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Bilenstri',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='CO2utslipp_g',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Chassisnr_VIN',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Drivstoff',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Effekt_Hk',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Farge',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Fargebeskrivelse',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Girkasse',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Hjuldrift',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Karosseri',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Km',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Omregistrering',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Priseksomreg',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Reg_nr',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Salgsform',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Sylindervolum',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Vekt',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='f1_gangregistrert',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='header',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='last_updated',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='totalpris',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='Årsavgift',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='Årsmodell',
            field=models.IntegerField(default=None),
        ),
    ]
