# Generated by Django 2.1.4 on 2019-07-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20190712_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Antalldrer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Antalleiere',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Antallseter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='CO2utslipp_g',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Effekt_Hk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Omregistrering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Priseksomreg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Sylindervolum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Vekt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='header',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='totalpris',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Årsmodell',
            field=models.IntegerField(default=0),
        ),
    ]
