# Generated by Django 2.1.4 on 2019-07-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20190712_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Antalldrer',
            field=models.IntegerField(default=1),
        ),
    ]
