# Generated by Django 2.1.4 on 2019-07-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20190712_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Antalldrer',
        ),
        migrations.AddField(
            model_name='car',
            name='Antallrer',
            field=models.IntegerField(default=0),
        ),
    ]
