# Generated by Django 2.1.4 on 2019-07-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20190712_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Km',
            new_name='Kmstand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='f1_gangregistrert',
            new_name='førstegangregistrert',
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
