# Generated by Django 2.1.4 on 2019-07-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20190712_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='førstegangregistrert',
            new_name='foorstegangregistrert',
        ),
    ]
