# Generated by Django 2.1.4 on 2019-07-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20190712_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Effekt_Hk',
            new_name='Effekt',
        ),
    ]
