# Generated by Django 2.1.4 on 2019-07-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20190712_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='CO2utslipp_g',
        ),
        migrations.AddField(
            model_name='car',
            name='CO2utslipp',
            field=models.IntegerField(default=0),
        ),
    ]
