# Generated by Django 2.1.4 on 2019-07-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20190712_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Chassisnr_VIN',
            new_name='ChassisnrVIN',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Reg_nr',
            new_name='Regnr',
        ),
    ]
