# Generated by Django 2.1.4 on 2019-07-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20190712_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Antallrer',
            new_name='Antalldører',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Bilenstri',
            new_name='Bilenståri',
        ),
    ]
