# Generated by Django 2.1.4 on 2019-07-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20190712_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='CO2utslipp',
        ),
        migrations.AddField(
            model_name='car',
            name='CO2utslip',
            field=models.IntegerField(default=0),
        ),
    ]
