# Generated by Django 2.1.4 on 2019-07-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20190712_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='CO2utslip',
            new_name='CO2utslipp',
        ),
    ]
