# Generated by Django 2.1.4 on 2019-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20190713_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Sylindervolum',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
