# Generated by Django 2.1.4 on 2019-07-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20190713_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Batterikapasitet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Finn_kode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Interiørfarge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='RekkeviddeWLTP',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
