# Generated by Django 2.1.4 on 2019-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_car_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
