# Generated by Django 2.1.4 on 2019-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_car_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='Finn_kode',
            field=models.CharField(blank=True, default=123, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
