# Generated by Django 2.1.4 on 2019-08-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_auto_20190726_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='solgt',
            field=models.BooleanField(default=False),
        ),
    ]
