# Generated by Django 2.1.4 on 2019-08-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_car_solgt'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
